name: ebump build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:21.3.8.2

    steps:
    - uses: actions/checkout@v1

    - name: Create escript
      run: make release

    - name: Upload ebump
      uses: actions/upload-artifact@v1
      with:
        name: ebump
        path: _build/default/bin/ebump

    - name: Create version.txt
      run: _build/default/bin/ebump version > version.txt

    - name: Upload ebump version artifact
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: version.txt

  release:
    needs: build

    runs-on: ubuntu-latest

    if: endsWith(github.ref, 'refs/heads/master')

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout
      uses: actions/checkout@v1

    - name: Download ebump
      uses: actions/download-artifact@v1
      with:
        name: ebump

    - name: Download version.txt
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Push Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      run: |
        go get -u github.com/tcnksm/ghr
        VERSION=$(cat version/version.txt | sed 's/Version: //')
        REPO=ebump
        OWNER=xaptum-eng
        $HOME/go/bin/ghr \
            -t ${GITHUB_TOKEN} \
            -u ${OWNER} \
            -r ${REPO} \
            -c ${GITHUB_SHA} \
            -delete \
            ${VERSION} ebump/ebump
